version: "3"

services:
  api:
    depends_on:
      - postgres

    build: .

    ports:
      - 8000:8000

    volumes:
      - ./:/usr/src/app:ro

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    # env_file:
    #   - ./.env
    
    environment:
      - DATABASE_HOSTNAME = postgres
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD = 1234
      - DATABASE_NAME = "fastapi crud system"
      - DATABASE_USERNAME = princewillingoo
      - SECRET_KEY = 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM = "HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES = 5000
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB="fastapi crud system"
    
    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db: